---
title: "Las Cruces cumulative annual precipitation"
author: "Francis Joyce"
date: "2021-02-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r include=FALSE}
library(tidyverse)
library(lubridate)
library(plotly)
library(viridis)
library(ggrepel)
library(here)
library(magrittr)
library(cowplot)

#suppress summarize info from dplyr
options(dplyr.summarise.inform = FALSE)
```

```{r}
#read in daily data from 2002-2008
LC_2005_2008 <- read.csv(here("data/LC_met_Jan05t_Jul08.csv"))

#remove 2 missing days of data (might want to do this downstream)
#reformat date columns 
daily_rain_2005_2008 <- LC_2005_2008 %>% 
   dplyr::filter(!is.na(precip)) %>% #remove 2 days missing data
  dplyr::mutate(date = paste(year, month, day, sep = "-")) %>% 
  dplyr::mutate(date = lubridate::ymd(date)) %>% 
  dplyr::mutate(daily_rain = precip) %>% 
  dplyr::mutate(JD = lubridate::yday(date)) %>% 
  dplyr::select(date, daily_rain, year, JD) 
 

```

```{r warning=FALSE, include=FALSE}

#read in 15-min data from 2008- 2020
LC_2008_2020 <- read.csv(here("data/datos_meteorologicos_LC_Aug08_Jun20.csv"), na.strings = "NA")


#reformat dates
LC_2008_2020 <- LC_2008_2020 %>%
  mutate(date = lubridate::dmy(LC_2008_2020$DATA_DATE2)) %>%
  mutate(year = lubridate::year(date)) %>%
  mutate (month = lubridate::month(date)) %>%
  mutate(day = lubridate::day(date)) %>%
  mutate(JD = lubridate::yday(date)) %>%
  mutate(yr = as.factor(year)) %>%
  mutate(rainfall = as.character(RAIN_MM_TOT)) %>%
  mutate(rainfall = as.numeric(rainfall)) 
 #didn't work to go straight from factor to numeric so converted to character first
  #na.omit #drops 13 cases with NAs


#summarize 2008-2020 rainfall by day
#added n column to see how many rows there were for each day
#15-min intervals: n = 96
#30-min intervals: n = 48
#n = some other value-> something is off


LC_rain_2008_2020 <- LC_2008_2020 %>% 
  select(c(date, year, month, day, yr, rainfall)) %>%
  na.omit %>% 
  group_by(date) %>% 
  summarize(daily_rain = sum(rainfall),
            n = n()) %>% 
  mutate(year = lubridate::year(date)) %>% 
  mutate(JD = lubridate::yday(date))

#remove 2020 data for now because it's a partial year (append below instead below)
daily_rain_2008_2019 <- LC_rain_2008_2020 %>% 
  dplyr::filter(lubridate::year(date) != 2020) 
   
```

```{r warning=FALSE}
#Downloaded and read in 2020 data in 6 batches (each 2 months?)

LC_2020A <- read.csv(here("data/Las_Cruces_2020/LC1.csv"))
LC_2020B <- read.csv(here("data/Las_Cruces_2020/LC2.csv"))
LC_2020C <- read.csv(here("data/Las_Cruces_2020/LC3.csv"))
LC_2020D <- read.csv(here("data/Las_Cruces_2020/LC4.csv"))
LC_2020E <- read.csv(here("data/Las_Cruces_2020/LC5.csv"))
LC_2020F <- read.csv(here("data/Las_Cruces_2020/LC6.csv"))

#combine 2020 batches into one dataframe
LC_2020 <- bind_rows(LC_2020A, 
                     LC_2020B, 
                     LC_2020C, 
                     LC_2020D, 
                     LC_2020E, 
                     LC_2020F)

#then clear individual batches from workspace
rm(LC_2020A, LC_2020B, LC_2020C,
   LC_2020D, LC_2020E, LC_2020F)

#clear out data frame with partial 2020 data
rm(LC_rain_2008_2020)


#reformat 2020 dates (and PAR column name)
LC_2020 <- LC_2020 %>% 
  mutate(date_time = lubridate::mdy_hm(Date.and.time.of.measurement)) %>% 
  mutate (PAR = Average.ps..active.Rad...) %>% 
  mutate(date = lubridate::date(date_time)) %>% 
  mutate(hour = lubridate::hour(date_time))


#now summarize 2020 rainfall by day
daily_rain_2020 <- LC_2020 %>% 
  group_by(date) %>% 
  summarize(daily_rain = sum(Rainfall)) %>% 
  dplyr::mutate(year = lubridate::year(date)) %>% 
  dplyr::mutate(JD = lubridate::yday(date)) %>% 
  drop_na() #somehow an NA row got in here (from one of the batches?), drop NA
```

```{r}

#read in 2021 data (single csv)
#note there seems to be a gap in the data between 2021-07-15 and 2021-07-24, partially inclusive
LC_2021 <- read.csv(here("data/LC_weather_2021.csv"))


#reformat dates
LC_2021 <- LC_2021 %>% 
  mutate(date_time = lubridate::mdy_hm(Date.and.time.of.measurement)) %>% 
  mutate(date = lubridate::date(date_time)) %>% 
  mutate(hour = lubridate::hour(date_time))

#summarize by day
daily_rain_2021 <- LC_2021 %>% 
  group_by(date) %>% 
  summarize(daily_rain = sum(Rainfall)) %>% 
  dplyr::mutate(year = lubridate::year(date)) %>% 
  dplyr::mutate(JD = lubridate::yday(date))

```
```{r}

#read in 2022 data
#Note that there is a gap in August
LC_2022 <- read.csv(here("data/2022/LC_Weather_2022.csv"))


#reformat dates
LC_2022 <- LC_2022 %>% 
  mutate(date_time = lubridate::mdy_hm(Date.and.time.of.measurement)) %>% 
  mutate(date = lubridate::date(date_time)) %>% 
  mutate(hour = lubridate::hour(date_time))



#summarize rainfall by day
daily_rain_2022 <- LC_2022 %>% 
  group_by(date) %>% 
  summarize(daily_rain = sum(Rainfall)) %>% 
  dplyr::mutate(year = lubridate::year(date)) %>% 
  dplyr::mutate(JD = lubridate::yday(date))

```

```{r}
LC_2023 <- read_csv(here("data/2023/LC_weather_2023.csv")) 

LC_2023 <- LC_2023 %>% 
  mutate(date_time = mdy_hm(`Date and time of measurement`)) %>% 
  mutate(date = lubridate::date(date_time)) %>% 
  mutate(hour = lubridate::hour(date_time))
  
#summarize rainfall by day
daily_rain_2023 <- LC_2023 %>% 
  group_by(date) %>% 
  summarize(daily_rain = sum(Rainfall)) %>% 
  dplyr::mutate(year = lubridate::year(date)) %>% 
  dplyr::mutate(JD = lubridate::yday(date))

```



# Finding and fixing missing data 

```{r}

#combine all individual data frames 2005 through 2022 into single data frame
LC_daily_rain <- bind_rows(daily_rain_2005_2008, daily_rain_2008_2019, daily_rain_2020, daily_rain_2021, daily_rain_2022, daily_rain_2023)

#check for missing dates (entirely missing rows, not missing values)

#create a sequence from start of date range to last date (i.e. no missing days)
date_range <- seq(ymd('2005-01-01'),ymd('2023-09-30'), by = '1 day')

#not sure this is needed
date_range <- as_date(date_range)

#number of days there should be is 6847 
length(date_range)

#number of days there are: 6800 
length(LC_daily_rain$date)

# number of missing days = 47
length(date_range)-length(LC_daily_rain$date)


#calculate percentage of missing dates that are missing data entirely

(length(date_range)-length(LC_daily_rain$date))/length(date_range)*100

#0.69% of days are missing


#find list of missing dates
missing_dates <- as_date(setdiff(date_range, LC_daily_rain$date))

#note that there may be data gaps shorter than 24 hrs that won't be reflected in this list. The way the 15-min data are summarized, they get a daily value even if there was a single period


#view(missing_dates)


#read in manually collected data [NOT COMPLETE]
#note that manually collected data are recorded at 07:00, so they do not correspond cleanly to the 24 hr periods in the summarized daily data. For manually collected data, data on each recorded date are mostly from the previous day (07-24h, vs. 00-07h)

#SO manually collected dates correspond to missing automated dates + 1 day



```


```{r warning=FALSE, include=FALSE}
#calculate annual totals...
rain_annual_totals <- LC_daily_rain %>% 
  dplyr::group_by(year) %>% 
  summarize(annual_rain = sum (daily_rain),
            days = n()) %>% #number of days with data
  mutate(date = str_c(year, "01-01", sep = "-") %>% lubridate::ymd())
```

### Static version

```{r echo=FALSE, message=FALSE, warning=FALSE}

#create data frame of dates for first day in each month to use as tick marks & labels
doy <- lubridate::date(
  c(
    "2016-01-01",
    "2016-02-01",
    "2016-03-01",
    "2016-04-01",
    "2016-05-01",
    "2016-06-01",
    "2016-07-01",
    "2016-08-01",
    "2016-09-01",
    "2016-10-01",
    "2016-11-01",
    "2016-12-01"
  )
)

#extract day of year (doy) using yday and also extract month for tick mark labels
doy <- tibble(mon = lubridate::month(doy, label = T),
              jul = lubridate::yday(doy))

#create data frame with cumulative annual rainfall by year
ytd <- LC_daily_rain %>%
  #filter(year != "1991") %>%
  group_by(year, .drop = FALSE) %>%
  mutate(cum_rain = cumsum(daily_rain)) %>% 
  ungroup() %>% 
  # group_by(year) %>% 
  # create column with "year" label
  mutate(year_label = case_when(
    year == 2007 & JD == 365 ~ year, 
    #year == 2008 & JD == 365 ~ year,
    #year == 6 & JD == 365 ~ year,
    year == 2010 & JD == 365 ~ year, 
    #year == 2021 & JD == 365 ~ year, 
    # for 2022
    year == 2022 & JD == 365 ~ year,
    year == 2023 & JD == 365 ~ year
  ))

LC_rain_mean <- LC_daily_rain %>%
  filter(year <2022) %>% 
  group_by(JD) %>% 
  summarize(mean_rain = mean(daily_rain)) %>% 
  ungroup()

ytd_mean <- LC_rain_mean %>% 
   mutate(cum_rain = cumsum(mean_rain))
  

mean_cumulative_curve <- ggplot(data = ytd_mean,
                                  aes(
                                    x = JD,
                                    y = mean_rain
                                  )) +
  geom_line() +
  scale_x_continuous(breaks = doy$jul,
                     labels = doy$mon,
                     limits = c(0, 380)) +
  #scale_y_continuous(breaks = seq(0,3500, 500)) +
  #scale_colour_viridis_c() +
  #scale_color_manual(values = cal_palette("kelp1")) +
  #scale_x_date(date_labels = "%b", date_breaks = "months") +
  labs(
    title = "Median cumulative precipitation",
    subtitle = "  Las Cruces 2005 to 2021",
    y = "Precipitation (mm)",
    x = "",
    caption = "2005-2021"
  )

mean_cumulative_curve

#create plot
cumulative_curves <-  ggplot(data = ytd,
                             aes(
                               x = JD,
                               y = cum_rain,
                               group = year,
                               color = year
                             )) +
  geom_line() +
  scale_x_continuous(breaks = doy$jul,
                     labels = doy$mon, 
                     expand = c(0,0.2)
                     ) +
  #scale_y_continuous(limits = c(0, 2000)) +
  #scale_y_continuous(breaks = seq(0,3500, 500)) +
  #scale_colour_viridis_c() +
  #scale_color_manual(values = cal_palette("kelp1")) +
  #scale_x_date(date_labels = "%b", date_breaks = "months") +
  labs(
    title = "Annual cumulative precipitation",
    subtitle = "Las Cruces 2005 to 2023",
    y = "Precipitation (mm)",
    x = "",
    caption = "2005-2023"
  ) +
  geom_text_repel(aes(x = JD + 20, y = cum_rain, label = year_label), direction = c("y"), hjust = 0) +
  scale_color_viridis() +
  #theme_bw() +
  theme(
    text = element_text(size = 15),
    axis.ticks.length.x = unit(0.5, "cm"),
    axis.text.x = element_text(vjust = 5.5,
                               hjust = -0.2)
  ) 
 

#print
cumulative_curves

#save figure to file. Note that because of the way Rmd handles filepaths, the filepath is relative to where the Rmd file is, not to the home directory. So this ends up in code/figures instead of just figures/
ggsave("figures/combined_cumulative_2023.png", plot = cumulative_curves, width = 8, height = 5)
```

### Interactive version

```{r echo=FALSE}
 ggplotly(cumulative_curves)
```


## Comparing Islas field season rainfall
```{r}
June_rainfall <- LC_daily_rain %>% 
  filter(JD>155) %>% 
  filter(JD<206) %>% 
  group_by(year) %>% 
  summarize(june_rain = sum(daily_rain))

summer_rain_2005_2021 <- June_rainfall %>% 
 filter(year != 2022)

median_rain <- median(summer_rain_2005_2021$june_rain)

summer_rainfall <- ggplot(data = June_rainfall, aes(x = year, y = june_rain)) +
  geom_col(fill = "dark blue") +
  geom_hline(yintercept = median_rain, linetype = 2) +
  geom_text(aes(label = round(june_rain)), nudge_y = 35)+
  labs(
    title = "Lluvia en temporada de muestreo Islas",
    subtitle = "Estación meteorológica Las Cruces: 6 de junio hasta 25 julio",
    y = "Precipitación (mm)",
    x = "año"
  ) 

summer_rainfall
```

```{r}
## Comparing June rainfall
June_rainfall <- LC_daily_rain %>% 
  filter(JD>152) %>% #1 June is doy 152
  filter(JD<181) %>% #30 June is doy 181 
  group_by(year) %>% 
  summarize(june_rain = sum(daily_rain))

june_rain_2005_2021 <- June_rainfall %>% 
 filter(year != 2022)

median_rain <- median(june_rain_2005_2021$june_rain)

June_rainfall_plot <- ggplot(data = June_rainfall, aes(x = year, y = june_rain)) +
  geom_col(fill = "dark blue") +
  geom_hline(yintercept = median_rain, linetype = 2) +
  geom_text(aes(label = round(june_rain)), nudge_y = 35)+
  labs(
    title = "Lluvia 1-30 junio",
    subtitle = "Estación meteorológica Las Cruces",
    caption = "Línea discontinua representa valor medio 2005-2021 (338 mm)",
    y = "Precipitación (mm)",
    x = "año"
  ) +
  scale_x_continuous(breaks = 2005:2023) +
  scale_y_continuous(expand = c(0,0), breaks = c(0,100, 200, 300, 400, 500, 600, 700), limits = c(0, 700)) +
  theme_minimal()

June_rainfall_plot
```


```{r}
spring_rainfall <- LC_daily_rain %>% 
  filter(JD>72) %>% 
  filter(JD<157) %>% 
  group_by(year) %>% 
  summarize(spring_rain = sum(daily_rain))

spring_rain_2005_2021 <- spring_rainfall %>% 
 filter(year != 2022)

median_spring_rain <- median(spring_rain_2005_2021$spring_rain)

spring_rainfall_plot <- ggplot(data = spring_rainfall, aes(x = year, y = spring_rain)) +
  geom_col() +
  geom_hline(yintercept = median_spring_rain, linetype = 2) +
  geom_text(aes(label = round(spring_rain)), nudge_y = 45)+
  labs(
    title = "Spring rainfall",
    subtitle = "LCBS ~13 March to 5 June",
    y = "Precipitación (mm)",
    x = "año"
  ) 

spring_rainfall_plot
```
## Total rainfall across years

```{r}
annual_rain <- LC_daily_rain %>% 
  group_by(year) %>% 
  summarize(annual_rainfall = round(sum(daily_rain))) %>% 
  mutate(annual_rain_m = round(annual_rainfall/1000, 2))


median_annual <- median(annual_rain$annual_rainfall)
  
  
annual_rain_plot <-
  ggplot(data = annual_rain, aes(
    x = year, 
    y = annual_rainfall)) +
  geom_col(fill = "dark blue")+
  ylab("Precipitación anual (mm)") +
  xlab("Año") +
  geom_text(aes(label = annual_rainfall), vjust = -0.2)+
  scale_x_continuous(breaks =c(2005:2023)) +
  scale_y_continuous(limits = c(0,5300), expand = c(0,0)) +
  geom_hline(yintercept = median_annual, linetype = 2)
  

annual_rain_plot

ggsave("annual_rain_2005_2023.png", annual_rain_plot, width = 7, height = 5)
```

##Low and high temperatures

```{r}

daily_temp_2022 <- LC_2022 %>% 
  group_by(date) %>% 
  summarize(high_temp = max(Max.Air.Temp),
            low_temp = min(Min.Air.Temp)) %>% 
  pivot_longer(high_temp:low_temp, names_to = "extrema") %>% 
  ungroup()

temp_colors <- c("red", "blue")

median_high <- daily_temp_2022 %>% 
  filter(extrema == "high_temp") %>% 
  select(value)

median_high <- median(median_high$value)

median_low <- daily_temp_2022 %>% 
  filter(extrema == "low_temp") %>% 
  select(value)

median_low <- median(median_low$value)

thermal_envelope <- ggplot(daily_temp_2022, aes(x = date, y = value, group = extrema)) +
  geom_line(aes(color = extrema)) +
  geom_hline(yintercept = c(median_high, median_low))


thermal_envelope

```

```{r}
#2023 monthly rain

#monthly rain in 2023
monthly_2023 <- daily_rain_2023 %>% 
   group_by(month = lubridate::floor_date(date, 'month')) %>% 
  summarize(monthly_rain = sum(daily_rain)) %>% 
  ungroup() %>% 
  mutate(month_numeric = month(month, label = TRUE))
 

#monthly rain in all years

monthly_rain <- ytd %>% 
  group_by(year, month = lubridate::floor_date(date, 'month')) %>% 
  summarize(monthly_rain = sum(daily_rain)) %>% 
  ungroup() %>% 
  mutate(month_numeric = month(month, label = TRUE)) %>% 
  group_by(month_numeric) %>%
  summarize(median_monthly_rain = median(monthly_rain)) %>% 
  ungroup()
  
monthly_rain_plot <- ggplot(data = monthly_rain, aes(x = month_numeric, y = median_monthly_rain)) +
  geom_col(data = monthly_2023, aes(x = month_numeric, y = monthly_rain)) + 
  scale_y_continuous(expand = c(0,10)) +
  geom_point() + 
  xlab("Month") +
  ylab("Rainfall") +
  labs(caption = "Points = median for 2005-2023, Bars = 2023 data")

  

monthly_rain_plot

ggsave("figures/monthly_median_vs_2023_rainfall.png", plot = monthly_rain_plot, width = 8, height = 5)
```
```{r}
#let's see how annual rainfall compares to ENSO status

#use the rsoi package
library(rsoi)
library(viridis)
library(RColorBrewer)
library(cowplot)

#download the ONI index (from NOAA?)
download_oni(use_cache = FALSE, file = here("data/ONI/ONI.csv"))

#read in
ONI <- read_csv(here("data/ONI/ONI.csv")) %>% 
  filter(Year > 2004) %>% 
  mutate(mon = lubridate::month(Date, label = TRUE))


#annual ONI

annual_ONI <- ONI %>% 
  group_by(Year) %>% 
  summarize(mean_ONI = mean(ONI, na.rm = TRUE)) %>% 
  ungroup()

#rainy season ONI

rainy_season_ONI <- ONI %>% 
  filter(! mon %in% c("Jan", "Feb", "Mar", "Dec")) %>% 
  group_by(Year) %>% 
  summarize(mean_ONI = mean(ONI)) %>%
  ungroup()
              


#set limits to center the divergent color scale
limit <- c(-2.7, 2.7)
  
#try plotting heatmap
p <-ggplot(ONI,aes(Year,mon,fill=ONI)) +
  geom_tile(color= "white") + 
  scale_fill_distiller(palette = "RdBu", limit = limit) +
  theme_cowplot() +
  ylab("Month")

p


#redo annual rain with bars color coded by ENSO status

#first need to join annual average ONI values to rainfall df

ONI_rain <- left_join(annual_rain, rainy_season_ONI, join_by(year == Year))


annual_limit <- c(-1.7,1.7)

ONI_rain_plot <-
  ggplot(data = ONI_rain, aes(
    x = year, 
    y = annual_rainfall, fill = mean_ONI)) +
  geom_col() +
  scale_fill_distiller(palette = "RdBu", limit = annual_limit) +
  ylab("Annual rainfall (mm)") +
  xlab("Year") +
  geom_text(aes(label = annual_rainfall), vjust = -0.2)+
  scale_x_continuous(breaks =c(2005:2023), expand = c(0.02,0.02)) +
  scale_y_continuous(limits = c(0,5300), expand = c(0,0)) +
  geom_hline(yintercept = median_annual, linetype = 2) +
  theme_dark() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  labs(fill ="Mean \n rainy season \n ONI") +
  labs(caption = "Rainy season is defined as Apr-Nov. \n Monthly ONI value corresponds to 3-month 'season.' \n Neutral phase is defined as -0.5 to +0.5 ONI.",
       title = "Annual rainfall and Oceanic Niño Index")
  

ONI_rain_plot

ggsave("figures/rainfall_ONI_timeseries.png", plot = ONI_rain_plot, width = 9, height = 5)
```


